import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import { useEffect, useState } from "react";
// const url = "http://localhost:1337/api/posts/1";
const url = "https://jsonplaceholder.typicode.com/posts?id=6"; 
// posts from jsonplaceholder

export async function getServerSideProps() {

    const res = await fetch(url);
    const data = await res.json();

  return {
    props: {
       posts : data,
    }, // will be passed to the page component as props
  };
}

export default function Home({posts}) {

  return (
    // console.log({todos}),
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      {/* <h1>Welcome</h1> */}
        {/* <p key={data.name}>{data.username}</p> */}
        {posts?.length === 0 ? (
        <div className={styles.myer}><p>
          User not found</p></div>
      ) : (
        posts?.map((post) => (
          <div>
          <h1>
             {post.title}
          </h1>
          <h3>
            {post.body}
          </h3>
          <p>
            {post.body}
          </p>
        </div>
        ))
        )}
    </div>
  )
}
